### ISSUE TITLE
About how to estimate the parameters of DINA

### ISSUE THREAD

**Issue by CherChen0** [inzhengda/DINA#1]

**Comment by CherChen0** [comment]
Hello, I am now doing some research in CDM, and I'm very interested in your work. But I am a little confused about the process of parameters estimation, so could you please tell me what reference you have refered to?

**Comment by CherChen0** [comment]
> No description provided.

**Comment by inzhengda** [comment]
The main paramater in DINA model is slip and guess of every problem.You coule give  init number of both like 0.1,and then use EM algorithm to calculate them untill the process is convergent.The paper <DINA Model and Parameter Estimation: A Didactic> by Jimmy de la Torre can help you a lot I think,very glad someone have interest about this.

**Comment by inzhengda** [comment]
> The main paramater in DINA model is slip and guess of every problem.You coule give init number of both like 0.1,and then use EM algorithm to calculate them untill the process is convergent.The paper by Jimmy de la Torre can help you a lot I think,very glad someone have interest about this.

The paper name : DINA Model and Parameter Estimation: A Didactic

**Comment by CherChen0** [comment]
Yes, I have read that paper, but I don't get how does it estimate the students' skill vectors. I see the     
estimation process considers all of the possibilities of skill vectors, so choose the one with the highest likelihood probability？

**Comment by inzhengda** [comment]
Yes,I guess so.The Appendix part in the papar provide us a method to calculate the slip and guess parameter for every problem.So after that ,we could get the likelihood matrix about every students and all of the possibilities of skill vectors,choose the bigest one as our prediction.
So in the experimental stage,we can use the predicte skill vector to verify whether the student could do the problem right,calculate some accuracy rate.
In fact,I still have some question in the appendix .The auther use combination of posterior probability instead of I0,R0,I1 and R1 inorder to calculate slip and guess .But I just use likelihood probability rather than posterior probability, because I don't konw prior probability distribution so assume every skill vector's prior probability is same.So the relation betwteen likelihood probability and posterior probability is direct ratio.We just choose the bigest one ,mabey it couble be better if we get the prior probability of skill vector.

**Comment by CherChen0** [comment]
Thank you so much! That helped a lot.
